"""Regenerate src/shelfkeep/generated/schema_version.py from migrations/."""

from pathlib import Path

root = Path(__file__).resolve().parent.parent
count = len(sorted((root / "migrations").glob("[0-9][0-9][0-9][0-9]_*.sql")))
(root / "src/shelfkeep/generated/schema_version.py").write_text(
    "# GENERATED by scripts/gen_schema_version.py from migrations/. Do not edit.\n"
    f"SCHEMA_VERSION = {count}\n",
    encoding="utf-8",
)
